name: 🐳 Build and push docker image
on:
  workflow_dispatch:
    inputs:
      servicio:
        description: 'Que parte quieres construir'
        type: choice
        required: true
        options:
        - cortador
#        - pusher
#        - rampa
        - reciver
#        - subtitle
      tag:
        description: que tag quieres ponerle a la imagen
        required: false
        default: latest
jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: CD into the directory
      run: cd ./${{ inputs.servicio }}

    - name: Log a Dockerhub
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fs-${{ inputs.servicio}}:${{ inputs.tags }} .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/fs-${{ inputs.servicio}}:${{ inputs.tags }}